import Head from 'next/head'
import styles from '../styles/Home.module.sass'

import Header from "../components/Header"
import MainLayout from '../components/layouts/MainLayout'
import ProductPreviews from "../components/ProductPreviews";
import ShopPreview from "../components/ShopPreview";
import ShopBySize from '../components/ShopBySize';
import ShopBy from '../components/ShopBy';
import BlogPreviews from "../components/BlogPreviews";
import Footer from "../components/Footer"
import { getCategoryFromSlug, getProductsByCategory, listCategories } from '../lib/commerce/productAPI';

export default function Home({ categories, lightCategory, growthCategory }) {

  // console.log(categories);

  const s = "size";
  const g = "genera";
  const l = "light";
  // console.log(lightCategory);

  // lightCategory.map(lc => console.log(lc));

  const monsterasContent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

  return (
    <div className={styles.container}>
      <Head>
        <title>Neat Houseplants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {/* <ProductPreviews 
        featuredProducts={featuredProducts}
      /> */}
      {/* <ShopPreview
        orientation={"left"}
        content={monsterasContent}
        imageSrc="/images/monsteras-home.jpg"
      /> */}
      <ShopBy 
        category={categories.filter(category => category.slug == "growth-direction")}
        tagline="Whichever direction, growth is growth"
      />
      <ShopBy 
        category={categories.filter(category => category.slug == "light")}
        tagline="Bright or dim, there's a plant for that"
      />
      
      <div className={styles.shopByChild}>
        <h3 className={styles.shopByTitle}>Whichever direction, growth is growth</h3>
          <ShopBySize 
            subText="Shop by style:"
          />
      </div>      
      <div className={styles.shopByChild}>
        <h3 className={styles.shopByTitle}>Fresh air and a healthy dog</h3>
          <ShopBySize 
            subText="Shop by specialty:"
          />
      </div>
      <div className={styles.shopByChild}>
        <h3 className={styles.shopByTitle}>Bright or dim, there's a plant for that</h3>
          <ShopBySize 
            subText="Shop by light:"
          />
      </div>

      <BlogPreviews />
    </div>
  )
};

Home.Layout = MainLayout;


export async function getStaticProps(){
  // const featuredProducts = await getProductsByCategory("featured");
  const categories = await listCategories();
  const growthCategory = await getCategoryFromSlug("growth-direction");
  const lightCategory = await getCategoryFromSlug("light");
    return {
      props: {
        categories,
        // featuredProducts,
        growthCategory,
        lightCategory
      }
  }
};