import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.sass'

import Navigation from "../components/Navigation"
import Header from "../components/Header"
import Main from "../components/Main"
import Footer from "../components/Footer"


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />
      <Header />
      {/* <Main /> */}
      {/* <Footer /> */}
      
      


    </div>
  )
}
